.\" -*- fill-column:100 -*-
.TH rsvg-convert 1
.SH NAME
rsvg-convert \- Render SVG documents to PNG images, or convert them to PDF or PS.
.SH SYNOPSIS
Convert an SVG to PNG at its "natural size" and write it to standard output:
.P
.RS
.B rsvg-convert
.I input.svg
.B >
.I output.png
.RE
.P
Specify an output filename; the input filename must be the last argument:
.P
.RS
.B rsvg-convert
.BI --output= output.png
.I input.svg
.RE
.P
Configure dots-per-inch (DPI), default is 96:
.P
.RS
.B rsvg-convert
.BI --dpi-x= 300
.BI --dpi-y= 300
.I input.svg
.B >
.I output.png
.RE
.P
Render an SVG at a specific pixel size, scaled proportionally:
.P
.RS
.B rsvg-convert
.BI --width= 1024
.BI --height= 768
.B --keep-aspect-ratio
.I input.svg
.B >
.I output.png
.RE
.P

.SH DESCRIPTION
.BR rsvg-convert
renders SVG documents into PNG raster images, or converts them to PDF or PS as vector objects.
By default
.BR rsvg-convert
will render an SVG document to a raster PNG image and write it to standard output:
.P
.RS
.B rsvg-convert
.I input.svg
.B >
.I output.png
.RE
.P
To select another format, use the
.B --format
option:
.P
.RS
.B rsvg-convert --format=pdf
.I input.svg
.B >
.I output.pdf
.RE
.P
Instead of standard output, the
.B --output
option lets you specify an output filename, or
.B -o
for short. Note that the input filename must be the last argument:
.P
.RS
.B rsvg-convert
.BI --output= output.png
.I input.svg
.RE
.P
You can use
.BR rsvg-convert
as part of a pipeline; without an argument for the input filename it will just use standard input:
.P
.RS
.B cat
.I input.svg
.B |
.B rsvg-convert
.B >
.I output.png
.RE
.P
.SS SPECIFYING AN OUTPUT SIZE
You can use the
.B --width
and
.B --height
options to specify the size of the output image.  Most of the time you should specify
.B --keep-aspect-ratio
to scale the image proportionally; for compatibility with old versions this is not the default.
.P
.RS
.B rsvg-convert
.BI --width= 100
.BI --height= 200
.B --keep-aspect-ratio
.I input.svg
.B >
.I output.png
.RE

.SS DEFAULT OUTPUT SIZE FOR RASTER IMAGES
If you do not specify options for the output size,
.BR rsvg-convert
will figure out a "natural size" for the SVG as follows:
.IP \(bu 2
.B SVG with width and height in pixel or physical units: 
The
.B width
and
.B height
attributes of the toplevel
.B <svg>
element get converted to pixels, based on the default dots-per-inch value, which is 96\ DPI.  You
can change this with the
.B --dpi-x
and
.B --dpi-y
options.  For example,
.B <svg\ width="1in"\ height="2in">
at 96\ DPI will get rendered as a 96*192\ pixel PNG.  If either of these attributes is in
.B
px
(pixel) units, it will be unchanged for the final size.
.IP \(bu 2
.B SVG with viewBox only:
The size of the
.B viewBox
attribute gets used for the pixel size of the image.  For example, 
.B <svg viewBox="0 0 20 30">
will create a 20*30\ pixel PNG.
.IP \(bu 2
.B SVG with width and height in percentages:
If the
.B width
and
.B height
attributes of the toplevel
.B <svg>
element are in percentage units, for example
.BR width="100%" ,
then they will be multiplied by the size of the
.B viewBox
attribute.  For example,
.B <svg width="50%" height="100" viewBox="0 0 20 30">
will be rendered as a 10*30\ pixel PNG.
.B Note that this behavior may change in the future.
.IP \(bu 2
.B SVG with no width, height, or viewBox:
.B rsvg-convert
will measure the extents of all graphical objects in the SVG document and render them at 1:1 scale
(1\ pixel for each CSS\ px\ unit).  It is strongly recommended that you give SVG documents an
explicit size with the
.B width, height,
or
.B viewBox
attributes.

.SS BACKGROUND COLOR
You can use the
.B --background-color
option (
.B -b
for short) to specify the backgroung color that will appear in parts of the image that would otherwise
be transparent.  This option accepts the same syntax as the CSS
.B color
property, so you can use
.B #rrggbb
syntax or CSS named colors like
.BR white .

.P
.RS
.B rsvg-convert
.BI --background-color= white
.I input.svg
.B >
.I output.png
#### opaque white
.RE
.P
.RS
.P
.B rsvg-convert
.B -b
.I '#ff000080'
.I input.svg
.B >
.I output.png
#### translucent red - use shell quotes so the # is not interpreted as a comment
.RE



.SH OPTIONS
.TP
.I "\-d \-\-dpi-x number"
Set the X resolution of the image in pixels per inch.  RSVG's current default is 96\ DPI.
.TP
.I "\-p \-\-dpi-y number"
Set the Y resolution of the image in pixels per inch.  RSVG's current default is 96\ DPI.
.TP
.I "\-x \-\-x\-zoom number"
X Zoom factor, as a percentage.  If unspecified, 1.0 is used as the default.
.TP
.I "\-y \-\-y\-zoom number"
Y Zoom factor, as a percentage.  If unspecified, 1.0 is used as the default.
.TP
.I "\-z \-\-zoom number"
Zoom factor, as a percentage.  If unspecified, 1.0 is used as the default.
.TP
.I "\-w \-\-width integer"
Specify how wide you wish the image to be.  If unspecified, the natural width of the image is used
as the default.
.TP
.I "\-h \-\-height integer"
Specify how tall you wish the image to be.  If unspecified, the natural height of the image is used
as the default.
.TP
.I "\-f \-\-format [png, pdf, ps, eps, svg]"
Specify the output format you wish the image to be saved in.  If unspecified, PNG is used as the
default.
.TP
.I "\-o \-\-output filename"
Specify the output filename.  If unspecified, outputs to stdout.
.TP
.I "\-i \-\-export-id object-id"
Allows to specify an SVG object that should be exported. If unspecified, all objects will be
exported.
.TP
.I "\-a \-\-keep-aspect-ratio"
Specify that the aspect ratio is to be preserved.  If unspecified, aspect ratio will not be
preserved.
.TP
.I "\-b \-\-background-color [black, white, #abccee, #aaa...]"
Specify the background color.  If unspecified, none is used as the default.
.TP
.I "\-s \-\-stylesheet filename"
Filename of a CSS stylesheet.
.TP
.I "\-l \-\-accept-language [es-MX,fr,en]"
Specify which languages will be used for SVG documents with multiple languages.  The string is
formatted like an HTTP Accept-Language header, which is a comma-separated list of BCP47 language
tags: https://www.rfc-editor.org/info/bcp47
.TP
.I "\-u \-\-unlimited"
The SVG parser has some guards designed to mitigate large CPU or memory consumption in the face of
malicious XML.  It may also refuse to resolve URIs used to embed image data.  If you are running
into such issues when converting a SVG, this option allows to turn off these guards.
.TP
.I "\-\-keep-image-data"
Include the original, compressed images in the final output, rather than uncompressed RGB data. This
is the default behavior for PDF and (E)PS output.
.TP
.I "\-\-no-keep-image-data"
Do not include the original, compressed images but instead embed uncompressed RGB date in PDF or
(E)PS output. This will most likely result in larger documents that are slower to read.
.TP
.I "\-v \-\-version"
Display what version of rsvg this is.
.SH ENVIRONMENT VARIABLES
.TP
.I "SOURCE_DATE_EPOCH"
If the selected output format is PDF, this variable can be used to control the CreationDate in the
PDF file.  This is useful for reproducible output.  The environment variable must be set to a
decimal number corresponding to a UNIX timestamp, defined as the number of seconds, excluding leap
seconds, since 01 Jan 1970 00:00:00 UTC.  The specification for this can be found at
https://reproducible-builds.org/specs/source-date-epoch/
.SH MORE INFORMATION
https://gitlab.gnome.org/GNOME/librsvg
https://wiki.gnome.org/Projects/LibRsvg

http://www.w3.org/TR/SVG11/
http://www.w3.org/TR/SVG2

http://www.gnome.org/
.SH "AUTHORS"
Dom Lachowicz (cinamod@hotmail.com), Caleb Moore (c.moore@student.unsw.edu.au), Federico
Mena-Quintero (federico@gnome.org), and a host of others.
