.TH rsvg-convert 1
.SH NAME
rsvg-convert \- turn SVG files into raster images.
.SH SYNOPSIS
.B rsvg-convert
[options] in.svg > out.png
.I ""
.SH DESCRIPTION
Converts SVG images into PNG raster images, PDF, PS, or SVG vector images, or dumps of Cairo XML or recording surfaces.
.SS OPTIONS
.TP
.I "\-d \-\-dpi-x number"
Set the X resolution of the image in pixels per inch. RSVG's current default is 90dpi
.TP
.I "\-p \-\-dpi-y number"
Set the Y resolution of the image in pixels per inch. RSVG's current default is 90dpi
.TP
.I "\-x \-\-x\-zoom number"
X Zoom factor, as a percentage. If unspecified, 1.0 is used as the default.
.TP
.I "\-y \-\-y\-zoom number"
Y Zoom factor, as a percentage. If unspecified, 1.0 is used as the default.
.TP
.I "\-z \-\-\-zoom number"
Zoom factor, as a percentage. If unspecified, 1.0 is used as the default.
.TP
.I "\-w \-\-width integer"
Specify how wide you wish the image to be. If unspecified, the natural width of the image is used as the default.
.TP
.I "\-h \-\-height integer"
Specify how tall you wish the image to be. If unspecified, the natural height of the image is used as the default.
.TP
.I "\-f \-\-format [png, pdf, ps, svg, xml, recording]"
Specify the output format you wish the image to be saved in. If unspecified, PNG is used as the default.
.TP
.I "\-o \-\-output filename"
Specify the output filename. If unspecified, outputs to stdout.
.TP
.I "\-a \-\-keep-aspect-ratio"
Specify that the aspect ratio is to be preserved. If unspecified, aspect ratio will not be preserved.
.TP
.I "\-b \-\-background-color [black, white, #abccee, #aaa...]"
Specify the background color. If unspecified, none is used as the default.
.TP
.I "\-\-base-uri uri"
Specify the base URI for SVG files. If unspecified, none is used as the default.
.TP
.I "\-v \-\-version"
Display what version of rsvg this is.
.SH MORE INFORMATION
http://librsvg.sourceforge.net/
http://www.w3.org/TR/SVG11/
http://www.gnome.org/
.SH "AUTHORS"
Dom Lachowicz (cinamod@hotmail.com), Caleb Moore (c.moore@student.unsw.edu.au), and a host of others.
