.TH rsvg 1
.SH NAME
rsvg \- Turn SVG files into raster images.
.SH SYNOPSIS
.B rsvg
[options] in.svg out.png
.I ""
.SH DESCRIPTION
RSVG coverts SVG images into PNG, JPEG, and ICO raster images.
.SS OPTIONS
.TP
.I "\-d \-\-dpi-x number"
Set the X resolution of the image in pixels per inch. RSVG's current default is 90dpi
.TP
.I "\-p \-\-dpi-y number"
Set the Y resolution of the image in pixels per inch. RSVG's current default is 90dpi
.TP
.I "\-x \-\-x\-zoom number"
X Zoom factor, as a percentage. If unspecified, 1.0 is used as the default.
.TP
.I "\-y \-\-y\-zoom number"
Y Zoom factor, as a percentage. If unspecified, 1.0 is used as the default.
.TP
.I "\-w \-\-width integer"
Specify how wide you wish the image to be. If unspecified, the natural width of the image is used as the default.
.TP
.I "\-h \-\-height integer"
Specify how tall you wish the image to be. If unspecified, the natural height of the image is used as the default.
.TP
.I "\-f \-\-format [png, jpeg, ico]"
Specify the output format you wish the image to be saved in. If unspecified, PNG is used as the default.
.TP
.I "\-q \-\-quality integer"
Specify JPEG compression factor. Number must be between 1 and 100, inclusive.
.TP
.I "\-v \-\-version"
Display what version of rsvg this is.
.SH MORE INFORMATION
http://librsvg.sourceforge.net/
http://www.w3.org/TR/SVG11/
http://www.gnome.org/
.SH "AUTHORS"
Dom Lachowicz (cinamod@hotmail.com), Caleb Moore (c.moore@student.unsw.edu.au), and a host of others.
