.TH rsvg 1
.SH NAME
rsvg \- Turn SVG files into raster images
.SH SYNOPSIS
.B rsvg
[option] file.svg file.png
.I ""
.SH DESCRIPTION
rsvg coverts SVG images into PNG and JPEG raster images
.SS OPTIONS
.TP
.I "\-d \-\-dpi number"
Set the resolution of the image in pixels per inch
.TP
.I "\-x \-\-x\-zoom number"
X Zoom factor, as a percentage
.TP
.I "\-y \-\-y\-zoom number"
Y Zoom factor, as a percentage
.TP
.I "\-w \-\-width integer"
Specify how wide you wish the image to be
.TP
.I "\-h \-\-height integer"
Specify how tall you wish the image to be
.TP
.I "\-f \-\-format [png, jpeg]"
Specify the output format you wish the image to be saved in
.TP
.I "\-v \-\-version"
Display what version of rsvg this is
.SH MORE INFORMATION
http://www.gnome.org/
http://librsvg.sourceforge.net/
http://www.w3.org/TR/SVG11/
.SH "AUTHORS"
Dom Lachowicz (cinamod@hotmail.com), Alex Larsson (alex@redhat.com), and a host of others
