[package]
name = "pixbufloader-svg"
version = "0.0.1"
authors = ["Alberto Ruiz <aruiz@gnome.org>"]
license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
cairo-rs = "0.19"
cstr = "0.2"
gdk-pixbuf = "0.19"
gio = "0.19"
glib = "0.19"
libc = "0.2"
librsvg = { path = "../rsvg" }
librsvg-c = { path = "../librsvg-c" }
