// This file was generated by gir (d50d839) from gir-files (???)
// DO NOT EDIT

mod handle;
pub use self::handle::Handle;
pub use self::handle::HandleExt;

mod flags;
pub use self::flags::HandleFlags;

#[doc(hidden)]
pub mod traits {
    pub use super::HandleExt;
}
