// Generated by gir (https://github.com/gtk-rs/gir @ 59e3912ac141)
// from ../builddir/rsvg (@ b1f110201820)
// from gir-files (@ 5c1e490fe50a)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "RsvgDimensionData", sizeof(RsvgDimensionData), alignof(RsvgDimensionData));
    printf("%s;%zu;%zu\n", "RsvgError", sizeof(RsvgError), alignof(RsvgError));
    printf("%s;%zu;%zu\n", "RsvgHandle", sizeof(RsvgHandle), alignof(RsvgHandle));
    printf("%s;%zu;%zu\n", "RsvgHandleClass", sizeof(RsvgHandleClass), alignof(RsvgHandleClass));
    printf("%s;%zu;%zu\n", "RsvgHandleFlags", sizeof(RsvgHandleFlags), alignof(RsvgHandleFlags));
    printf("%s;%zu;%zu\n", "RsvgLength", sizeof(RsvgLength), alignof(RsvgLength));
    printf("%s;%zu;%zu\n", "RsvgPositionData", sizeof(RsvgPositionData), alignof(RsvgPositionData));
    printf("%s;%zu;%zu\n", "RsvgRectangle", sizeof(RsvgRectangle), alignof(RsvgRectangle));
    printf("%s;%zu;%zu\n", "RsvgUnit", sizeof(RsvgUnit), alignof(RsvgUnit));
    return 0;
}
