// Generated by gir (https://github.com/gtk-rs/gir @ 59e3912ac141)
// from ../builddir/rsvg (@ b1f110201820)
// from gir-files (@ 5c1e490fe50a)
// DO NOT EDIT

#[cfg(not(docsrs))]
use std::process;

#[cfg(docsrs)]
fn main() {} // prevent linking libraries to avoid documentation failure

#[cfg(not(docsrs))]
fn main() {
    if let Err(s) = system_deps::Config::new().probe() {
        println!("cargo:warning={s}");
        process::exit(1);
    }
}
