// Generated by gir (https://github.com/gtk-rs/gir @ 88f37d4165a8)
// from ../builddir/rsvg (@ 5bf47e852751)
// from gir-files (@ 6cef10cd64df)
// DO NOT EDIT

fn main() {
    if std::env::var("DOCS_RS").is_ok() {
        // prevent linking libraries to avoid documentation failure
        return;
    }

    if let Err(s) = system_deps::Config::new().probe() {
        println!("cargo:warning={s}");
        std::process::exit(1);
    }
}
