[package]
name = "librsvg-rebind-sys"
authors = ["Sophie Herold <sophie@hemio.de>"]
version = "0.2.1"
description = "FFI bindings for librsvg"
homepage = "https://gitlab.gnome.org/GNOME/librsvg"
license = "MIT"
repository = "https://gitlab.gnome.org/GNOME/librsvg"
documentation = "https://gnome.pages.gitlab.gnome.org/librsvg/doc/librsvg_rebind_sys/"
categories = ["api-bindings"]
edition = "2021"
build = "build.rs"
keywords = ["svg"]
links = "rsvg"
exclude = ["Gir.toml", "tests/"]

[package.metadata.docs.rs]
rustc-args = ["--cfg", "docsrs"]
rustdoc-args = ["--cfg", "docsrs", "--generate-link-to-definition"]
all-features = true

[package.metadata.system-deps.librsvg_2_0]
name = "librsvg-2.0"
version = "2.50"

[package.metadata.system-deps.librsvg_2_0.v2_58]
version = "2.58"

[package.metadata.system-deps.librsvg_2_0.v2_59]
version = "2.59"

[dependencies]
libc.workspace = true

[dependencies.gdk-pixbuf-sys]
workspace = true

[dependencies.cairo-sys-rs]
workspace = true

[dependencies.glib-sys]
workspace = true

[dependencies.gio-sys]
workspace = true

[dependencies.gobject-sys]
workspace = true

[build-dependencies]
system-deps = "7"

[dev-dependencies]
shell-words.workspace = true
tempfile.workspace = true

[features]
v2_58 = []
v2_59 = ["v2_58"]
